# Generated by Django 3.2 on 2021-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.CharField(max_length=50)),
                ('buyer', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('open', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('minimum_capacity', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
