# Generated by Django 3.2 on 2021-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_bids_buyers_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
