# Generated by Django 3.2 on 2021-05-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20210503_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
