# Generated by Django 3.2 on 2021-05-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_buyers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='competitions.bids'),
        ),
    ]
