# Generated by Django 3.2 on 2021-05-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20210503_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.sellers'),
        ),
    ]
