# Generated by Django 3.2 on 2021-05-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_bids_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.sellers'),
        ),
    ]
