# Generated by Django 3.2 on 2021-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_alter_bids_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='competition',
        ),
    ]
