# Generated by Django 3.2 on 2021-05-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_remove_bids_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='seller',
        ),
        migrations.AddField(
            model_name='bids',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions'),
        ),
    ]
