# Generated by Django 3.2 on 2021-05-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20210503_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.sellers'),
        ),
    ]
