# Generated by Django 3.2 on 2021-05-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_bids_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='offered_capacity',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='value',
        ),
        migrations.RemoveField(
            model_name='buyers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sellers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sellers',
            name='verified',
        ),
    ]
