# Generated by Django 3.2 on 2021-05-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_auto_20210503_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='sellers',
        ),
        migrations.RemoveField(
            model_name='competitions',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='buyers',
        ),
    ]
