# Generated by Django 3.2 on 2021-05-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_bids_buyers_sellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='competition',
        ),
        migrations.DeleteModel(
            name='competitions',
        ),
    ]
