# Generated by Django 3.2 on 2021-05-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20210503_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='competitions',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('open', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('minimum_capacity', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.buyers')),
            ],
        ),
        migrations.AddField(
            model_name='bids',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competitions'),
        ),
    ]
