# Generated by Django 3.2 on 2021-05-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_alter_sellers_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.sellers'),
        ),
    ]
