# Generated by Django 3.2 on 2021-05-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_alter_bids_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='closedCompetitionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('associatedBuyer', models.CharField(max_length=225)),
                ('totalValueAcceptedBids', models.IntegerField()),
                ('offeredCapacity', models.IntegerField()),
                ('percentageAcceptedBids', models.FloatField()),
            ],
        ),
    ]
