# Generated by Django 3.2 on 2021-05-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_auto_20210505_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedcompetitiondata',
            name='associatedBuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.buyers'),
        ),
    ]
