# Generated by Django 3.2 on 2021-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_alter_closedcompetitiondata_associatedbuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedcompetitiondata',
            name='associatedBuyer',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
