# Generated by Django 3.2 on 2021-05-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_alter_closedcompetitiondata_associatedbuyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedcompetitiondata',
            name='totalValueAcceptedBids',
        ),
    ]
